# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npx truffle compile
    npx truffle test
  displayName: 'npm install and build'

# Publish Test Results
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
    testResultsFiles: '**/TEST-*.xml' 

- script: |
    npx solidity-coverage
    npx istanbul report --include coverage.json --dir ./cobertura-coverage cobertura
    npx istanbul report --include coverage.json --dir ./cobertura-coverage html
  displayName: 'run coverage tool'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura' # Options: cobertura, jaCoCo
    summaryFileLocation: '**/cobertura-coverage.xml'
    reportDirectory: '**/cobertura-coverage'
    #additionalCodeCoverageFiles: # Optional
    #failIfCoverageEmpty: false # Optional